[package]
name = "cli-street"
version = "0.1.0"
edition = "2021"

[dependencies]
alphavantage = "0.7.0"
crossterm = "0.28.1"
dotenv = "0.15.0"
futures = "0.3.31"
ratatui = "0.28.1"
reqwest = "0.12.8"
serde = "1.0.210"
tokio = { version = "1.40.0", features = ["full"] }